%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 24-Apr-2026 13:27:33
                     ConfigInfos.Version = '25.2.0.3150157 (R2025b) Update 4';
                   ConfigInfos.SessionID = 'ConfiguredVirtualVehicle.m';
                   ConfigInfos.LicStatus = [1,1,1,1,1,1,1,1,1];
                ConfigInfos.ProjPathText = 'C:\Users\Omen\Desktop\TemeFac\AN2\SiemensHackaton\code-the-future-2026-briliant-minds';
                    ConfigInfos.ProjPath = 'C:\Users\Omen\Desktop\TemeFac\AN2\SiemensHackaton\code-the-future-2026-briliant-minds\VirtualMoto\VirtualMoto';
                 ConfigInfos.SessionName = 'SiemensCicle';
                 ConfigInfos.XmlPathText = '';
               ConfigInfos.TemplateModel = 'VirtualMotoTemplate';
          ConfigInfos.TemplatePlantModel = 'In_Plane_ModelArchitecture';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
            ConfigInfos.ConfigPlantModel = '';
                    ConfigInfos.VehClass = 'Motorcycle';
                     ConfigInfos.VehArct = 'Conventional Motorcycle with Chain Drive';
                      ConfigInfos.VehDyn = 0;
              ConfigInfos.PlantModelType = 'Simscape';
                  ConfigInfos.VehChassis = 'In-Plane Model';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Body and Frame') = 'In-Plane Model';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop Controller';
ConfigInfos.FeatureVariantSelectedMap('Chain') = 'Chain/Belt Drive';
ConfigInfos.FeatureVariantSelectedMap('Engine Control Unit') = 'Simple ECU';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Ambient Conditions';
ConfigInfos.FeatureVariantSelectedMap('Front Brakes') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Front Suspension') = 'Linear Spring and Damper Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire and Wheel') = 'Linear Tire Front';
ConfigInfos.FeatureVariantSelectedMap('Motorcycle Architecture') = 'Conventional Motorcycle with Chain Drive';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Conventional Motorcycle';
ConfigInfos.FeatureVariantSelectedMap('Propulsion System') = 'SI Mapped Engine';
ConfigInfos.FeatureVariantSelectedMap('Rear Brakes') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Rear Suspension') = 'Linear Spring and Damper Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire and Wheel') = 'Linear Tire Rear';
ConfigInfos.FeatureVariantSelectedMap('Rider') = 'Rigid';
ConfigInfos.FeatureVariantSelectedMap('Rider Control') = 'Longitudinal Rider';
ConfigInfos.FeatureVariantSelectedMap('Steering Damper') = 'No Damper';
ConfigInfos.FeatureVariantSelectedMap('Steering System') = 'No Steering';
ConfigInfos.FeatureVariantSelectedMap('Transmission Control Unit') = 'Rider Pass Through';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'No VCU';

%% User Modified Data
            ConfigInfos.DataModified=[];

%% Test Plan
          ConfigInfos.TestPlan{1}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{1}.Name = 'Drive Cycle';
           ConfigInfos.TestPlan{1}.Cycle = 'FTP75';
          ConfigInfos.TestPlan{1}.Driver = 'Longitudinal Rider';
       ConfigInfos.TestPlan{1}.Data{1,1} = 'ScnSimTime';
       ConfigInfos.TestPlan{1}.Data{1,2} = '2474';
       ConfigInfos.TestPlan{1}.Data{2,1} = 'InitRearCntctPtchLongVel';
       ConfigInfos.TestPlan{1}.Data{2,2} = '0';

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Body.Genrl.Vel.xdot',...
'Body.Genrl.Ang.thetafrm',...
'Body.Genrl.AngVel.thetafrmdot',...
'RearArm.Genrl.Ang.thetara',...
'Body.BdyFrm.Cg.Acc.ax',...
'Body.BdyFrm.Cg.Acc.ay',...
'RearArm.Genrl.AngVel.thetaradot',...
'Driveline.EngSpd',...
'Wheels.RearTire.Omega',...
};

%% Finish
